version: '3.4'

services:
  dogclassification:
    image: dogclassification
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - "../:/workspace"